# Generated by Django 5.2.1 on 2025-07-11 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto')], verbose_name='Tipo de Evento')),
                ('event_datetime', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_set', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
                'permissions': [('edit_own_event_24h', 'Can edit own events within 24 hours'), ('delete_own_event_24h', 'Can delete own events within 24 hours')],
                'indexes': [models.Index(fields=['patient', '-event_datetime'], name='event_patient_dt_idx'), models.Index(fields=['created_by', '-event_datetime'], name='event_creator_dt_idx'), models.Index(fields=['event_datetime'], name='event_datetime_idx'), models.Index(fields=['event_type', '-event_datetime'], name='event_type_dt_idx'), models.Index(fields=['patient', 'event_type', '-event_datetime'], name='event_pt_type_dt_idx')],
            },
        ),
    ]
