# Generated by Django 5.2.1 on 2025-07-28 00:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto'), (11, 'Formulário PDF'), (12, 'Alteração de Prontuário'), (13, 'Admissão Hospitalar'), (14, 'Alta Hospitalar'), (15, 'Alteração de Status'), (16, 'Admissão de Emergência'), (17, 'Transferência'), (18, 'Declaração de Óbito'), (19, 'Status Ambulatorial')], verbose_name='Tipo de Evento')),
                ('event_datetime', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_set', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
                'permissions': [('edit_own_event_24h', 'Can edit own events within 24 hours'), ('delete_own_event_24h', 'Can delete own events within 24 hours')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('admission_type', models.CharField(help_text='Tipo da admissão hospitalar', max_length=20, verbose_name='Tipo de Admissão')),
                ('initial_bed', models.CharField(blank=True, help_text='Leito/quarto inicial', max_length=20, verbose_name='Leito Inicial')),
                ('admission_diagnosis', models.TextField(blank=True, help_text='Diagnóstico principal na admissão', verbose_name='Diagnóstico de Admissão')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_event', to='patients.patientadmission', verbose_name='Internação')),
            ],
            options={
                'verbose_name': 'Evento de Admissão',
                'verbose_name_plural': 'Eventos de Admissão',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='DischargeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('discharge_type', models.CharField(help_text='Tipo da alta hospitalar', max_length=20, verbose_name='Tipo de Alta')),
                ('final_bed', models.CharField(blank=True, help_text='Último leito/quarto', max_length=20, verbose_name='Leito Final')),
                ('discharge_diagnosis', models.TextField(blank=True, help_text='Diagnóstico principal na alta', verbose_name='Diagnóstico de Alta')),
                ('stay_duration_days', models.IntegerField(blank=True, help_text='Duração total em dias', null=True, verbose_name='Duração da Internação (dias)')),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_timeline_event', to='patients.patientadmission', verbose_name='Internação')),
            ],
            options={
                'verbose_name': 'Evento de Alta',
                'verbose_name_plural': 'Eventos de Alta',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='RecordNumberChangeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('old_record_number', models.CharField(blank=True, help_text='Número de prontuário anterior', max_length=50, verbose_name='Número Anterior')),
                ('new_record_number', models.CharField(help_text='Novo número de prontuário', max_length=50, verbose_name='Novo Número')),
                ('change_reason', models.TextField(blank=True, help_text='Razão para a mudança do número', verbose_name='Motivo da Alteração')),
                ('record_change', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_event', to='patients.patientrecordnumber', verbose_name='Alteração de Prontuário')),
            ],
            options={
                'verbose_name': 'Evento de Alteração de Prontuário',
                'verbose_name_plural': 'Eventos de Alteração de Prontuário',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='StatusChangeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('previous_status', models.PositiveSmallIntegerField(verbose_name='Status Anterior')),
                ('new_status', models.PositiveSmallIntegerField(verbose_name='Novo Status')),
                ('reason', models.TextField(blank=True, verbose_name='Motivo da Alteração')),
                ('bed', models.CharField(blank=True, max_length=20, verbose_name='Leito')),
                ('discharge_reason', models.TextField(blank=True, verbose_name='Motivo da Alta')),
                ('death_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora do Óbito')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.ward', verbose_name='Ala')),
            ],
            options={
                'verbose_name': 'Evento de Alteração de Status',
                'verbose_name_plural': 'Eventos de Alteração de Status',
            },
            bases=('events.event',),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['patient', '-event_datetime'], name='event_patient_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-event_datetime'], name='event_creator_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_datetime'], name='event_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', '-event_datetime'], name='event_type_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['patient', 'event_type', '-event_datetime'], name='event_pt_type_dt_idx'),
        ),
    ]
