# Generated by Django 5.2.1 on 2025-06-11 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['patient', '-event_datetime'], name='event_patient_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-event_datetime'], name='event_creator_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_datetime'], name='event_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', '-event_datetime'], name='event_type_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['patient', 'event_type', '-event_datetime'], name='event_pt_type_dt_idx'),
        ),
    ]
