# Generated by Django 5.2.1 on 2026-01-13 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft_created_by_bot',
            field=models.CharField(blank=True, help_text='Client ID do bot que criou o rascunho', max_length=255, verbose_name='Criado por Bot'),
        ),
        migrations.AddField(
            model_name='event',
            name='draft_delegated_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que delegou permissão ao bot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Delegado por'),
        ),
        migrations.AddField(
            model_name='event',
            name='draft_expires_at',
            field=models.DateTimeField(blank=True, help_text='Quando o rascunho expira automaticamente', null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Indica se este evento é um rascunho criado por bot', verbose_name='É Rascunho'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='draft_created_by_bot',
            field=models.CharField(blank=True, help_text='Client ID do bot que criou o rascunho', max_length=255, verbose_name='Criado por Bot'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='draft_delegated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que delegou permissão ao bot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Delegado por'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='draft_expires_at',
            field=models.DateTimeField(blank=True, help_text='Quando o rascunho expira automaticamente', null=True, verbose_name='Expira em'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Indica se este evento é um rascunho criado por bot', verbose_name='É Rascunho'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_draft', 'draft_expires_at'], name='event_draft_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['draft_created_by_bot'], name='event_draft_bot_idx'),
        ),
    ]
