# Generated by Django 5.2.1 on 2025-06-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto')], verbose_name='Tipo de Evento'),
        ),
    ]
