# Generated by Django 5.2.1 on 2025-06-09 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('patients', '0006_add_patient_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['patient', '-event_datetime'], name='event_patient_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-event_datetime'], name='event_creator_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_datetime'], name='event_datetime_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', '-event_datetime'], name='event_type_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['patient', 'event_type', '-event_datetime'], name='event_pt_type_dt_idx'),
        ),
    ]
