# Generated by Django 5.2.1 on 2026-01-13 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_draft_created_by_bot_event_draft_delegated_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft_promoted_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o rascunho foi promovido a definitivo', null=True, verbose_name='Promovido em'),
        ),
        migrations.AddField(
            model_name='event',
            name='draft_promoted_by',
            field=models.ForeignKey(blank=True, help_text='Usuário que promoveu este rascunho a definitivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_drafts', to=settings.AUTH_USER_MODEL, verbose_name='Promovido por'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='draft_promoted_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o rascunho foi promovido a definitivo', null=True, verbose_name='Promovido em'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='draft_promoted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que promoveu este rascunho a definitivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Promovido por'),
        ),
    ]
