# Generated by Django 6.0.1 on 2026-04-14 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfileChangeEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('changed_fields', models.TextField(blank=True, help_text='Lista ordenada de campos alterados (nomes internos, separados por vírgula)', verbose_name='Campos Alterados')),
                ('change_summary', models.TextField(blank=True, help_text='Texto renderizável para fallback de card', verbose_name='Resumo da Alteração')),
                ('previous_values', models.JSONField(blank=True, default=dict, help_text='JSON com valores anteriores dos campos alterados', verbose_name='Valores Anteriores')),
                ('new_values', models.JSONField(blank=True, default=dict, help_text='JSON com novos valores dos campos alterados', verbose_name='Novos Valores')),
            ],
            options={
                'verbose_name': 'Evento de Alteração de Perfil',
                'verbose_name_plural': 'Eventos de Alteração de Perfil',
            },
            bases=('events.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto'), (11, 'Formulário PDF'), (12, 'Alteração de Prontuário'), (13, 'Admissão Hospitalar'), (14, 'Alta Hospitalar'), (15, 'Alteração de Status'), (16, 'Admissão de Emergência'), (17, 'Transferência'), (18, 'Declaração de Óbito'), (19, 'Status Ambulatorial'), (20, 'Tag Adicionada'), (21, 'Tag Removida'), (22, 'Tags Removidas em Lote'), (23, 'Termo de Consentimento'), (24, 'Alteração de Perfil')], verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto'), (11, 'Formulário PDF'), (12, 'Alteração de Prontuário'), (13, 'Admissão Hospitalar'), (14, 'Alta Hospitalar'), (15, 'Alteração de Status'), (16, 'Admissão de Emergência'), (17, 'Transferência'), (18, 'Declaração de Óbito'), (19, 'Status Ambulatorial'), (20, 'Tag Adicionada'), (21, 'Tag Removida'), (22, 'Tags Removidas em Lote'), (23, 'Termo de Consentimento'), (24, 'Alteração de Perfil')], verbose_name='Tipo de Evento'),
        ),
    ]
