# Generated by Django 5.2.1 on 2025-10-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeReport',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('admission_date', models.DateField(help_text='Data da admissão hospitalar', verbose_name='Data de Admissão')),
                ('discharge_date', models.DateField(help_text='Data da alta hospitalar', verbose_name='Data de Alta')),
                ('admission_history', models.TextField(help_text='História clínica da admissão', verbose_name='História da Admissão')),
                ('problems_and_diagnosis', models.TextField(help_text='Problemas principais e diagnósticos', verbose_name='Problemas e Diagnósticos')),
                ('exams_list', models.TextField(help_text='Exames realizados durante a internação', verbose_name='Lista de Exames')),
                ('procedures_list', models.TextField(help_text='Procedimentos realizados', verbose_name='Lista de Procedimentos')),
                ('inpatient_medical_history', models.TextField(help_text='Evolução médica durante a internação', verbose_name='História Médica da Internação')),
                ('discharge_status', models.TextField(help_text='Condições do paciente na alta', verbose_name='Status da Alta')),
                ('discharge_recommendations', models.TextField(help_text='Orientações e recomendações para pós-alta', verbose_name='Recomendações de Alta')),
                ('medical_specialty', models.CharField(help_text='Especialidade responsável pela alta', max_length=100, verbose_name='Especialidade Médica')),
            ],
            options={
                'verbose_name': 'Relatório de Alta',
                'verbose_name_plural': 'Relatórios de Alta',
                'ordering': ['-event_datetime'],
                'indexes': [models.Index(fields=['admission_date'], name='dischargere_admissi_e580e3_idx'), models.Index(fields=['discharge_date'], name='dischargere_dischar_08da36_idx'), models.Index(fields=['medical_specialty'], name='dischargere_medical_1f573d_idx')],
            },
            bases=('events.event',),
        ),
    ]
