# Generated by Django 5.2.1 on 2026-01-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dischargereports', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DROP INDEX IF EXISTS dischargere_is_draf_26e620_idx;"
                "ALTER TABLE dischargereports_dischargereport DROP COLUMN IF EXISTS is_draft;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
