# Generated by Django 5.2.1 on 2026-01-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dischargereports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dischargereport',
            name='dischargere_is_draf_26e620_idx',
        ),
        migrations.RemoveField(
            model_name='dischargereport',
            name='is_draft',
        ),
    ]
