# Generated by Django 5.2.1 on 2025-06-29 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto')], verbose_name='Tipo de Evento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_content_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sample_content_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Conteúdo de Exemplo',
                'verbose_name_plural': 'Conteúdos de Exemplo',
                'ordering': ['event_type', 'title'],
                'indexes': [models.Index(fields=['event_type'], name='sample_content_event_type_idx'), models.Index(fields=['created_at'], name='sample_content_created_at_idx')],
            },
        ),
    ]
