# Generated by Django 6.0.4 on 2026-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplecontent',
            name='event_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto'), (11, 'Formulário PDF'), (12, 'Alteração de Prontuário'), (13, 'Admissão Hospitalar'), (14, 'Alta Hospitalar'), (15, 'Alteração de Status'), (16, 'Admissão de Emergência'), (17, 'Transferência'), (18, 'Declaração de Óbito'), (19, 'Status Ambulatorial'), (20, 'Tag Adicionada'), (21, 'Tag Removida'), (22, 'Tags Removidas em Lote'), (23, 'Termo de Consentimento'), (24, 'Alteração de Perfil')], verbose_name='Tipo de Evento'),
        ),
    ]
