# Generated by Django 5.2.1 on 2025-06-29 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome descritivo para o template de prescrição', max_length=200, verbose_name='Nome do Template')),
                ('is_public', models.BooleanField(default=False, help_text='Se marcado, outros usuários poderão ver este template', verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Prescrição',
                'verbose_name_plural': 'Templates de Prescrições',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200, verbose_name='Nome do Medicamento')),
                ('presentation', models.CharField(help_text='Dosagem, forma farmacêutica, concentração', max_length=300, verbose_name='Apresentação')),
                ('usage_instructions', models.TextField(help_text='Instruções detalhadas de uso', verbose_name='Instruções de Uso')),
                ('quantity', models.CharField(help_text='Quantidade a ser dispensada', max_length=100, verbose_name='Quantidade')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do item no template', verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='drugtemplates.prescriptiontemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Item do Template de Prescrição',
                'verbose_name_plural': 'Itens dos Templates de Prescrições',
                'ordering': ['template', 'order', 'drug_name'],
            },
        ),
        migrations.CreateModel(
            name='DrugTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Medicamento')),
                ('presentation', models.CharField(max_length=300, verbose_name='Apresentação')),
                ('usage_instructions', models.TextField(help_text='Instruções detalhadas de uso (suporte a markdown)', verbose_name='Instruções de Uso')),
                ('is_public', models.BooleanField(default=False, help_text='Se marcado, outros usuários poderão ver este template', verbose_name='Público')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Número de vezes que este template foi utilizado em prescrições', verbose_name='Contador de Uso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Medicamento',
                'verbose_name_plural': 'Templates de Medicamentos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='drugtemplates_name_idx'), models.Index(fields=['creator'], name='drugtemplates_creator_idx'), models.Index(fields=['is_public'], name='drugtemplates_is_public_idx'), models.Index(fields=['created_at'], name='drugtemplates_created_at_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['name'], name='presc_tmpl_name_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['creator'], name='presc_tmpl_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['is_public'], name='presc_tmpl_public_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplate',
            index=models.Index(fields=['created_at'], name='presc_tmpl_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplateitem',
            index=models.Index(fields=['template'], name='presc_item_tmpl_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplateitem',
            index=models.Index(fields=['drug_name'], name='presc_item_drug_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptiontemplateitem',
            index=models.Index(fields=['order'], name='presc_item_order_idx'),
        ),
    ]
