# Generated by Django 6.0.1 on 2026-01-18 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtemplates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='drugtemplate',
            new_name='drugtpl_name_idx',
            old_name='drugtemplates_name_idx',
        ),
        migrations.RenameIndex(
            model_name='drugtemplate',
            new_name='drugtpl_creator_idx',
            old_name='drugtemplates_creator_idx',
        ),
        migrations.RenameIndex(
            model_name='drugtemplate',
            new_name='drugtpl_public_idx',
            old_name='drugtemplates_is_public_idx',
        ),
        migrations.RenameIndex(
            model_name='drugtemplate',
            new_name='drugtpl_created_idx',
            old_name='drugtemplates_created_at_idx',
        ),
        migrations.AddField(
            model_name='drugtemplate',
            name='concentration',
            field=models.CharField(blank=True, default='', help_text='Concentração do medicamento (ex: 500 mg, 40 mg/mL)', max_length=100, verbose_name='Concentração'),
        ),
        migrations.AddField(
            model_name='drugtemplate',
            name='import_source',
            field=models.CharField(blank=True, help_text='Fonte da importação (ex: MERGED_medications.csv)', max_length=200, null=True, verbose_name='Fonte de Importação'),
        ),
        migrations.AddField(
            model_name='drugtemplate',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='True se o medicamento foi importado de fonte externa', verbose_name='Importado'),
        ),
        migrations.AddField(
            model_name='drugtemplate',
            name='pharmaceutical_form',
            field=models.CharField(blank=True, default='', help_text='Forma farmacêutica (ex: comprimido, solução injetável, cápsula)', max_length=100, verbose_name='Forma Farmacêutica'),
        ),
        migrations.AlterField(
            model_name='drugtemplate',
            name='presentation',
            field=models.CharField(blank=True, help_text='Campo legado - será preenchido automaticamente', max_length=300, verbose_name='Apresentação'),
        ),
        migrations.AlterField(
            model_name='drugtemplate',
            name='usage_instructions',
            field=models.TextField(blank=True, help_text='Instruções detalhadas de uso (suporte a markdown)', null=True, verbose_name='Instruções de Uso'),
        ),
        migrations.AddIndex(
            model_name='drugtemplate',
            index=models.Index(fields=['concentration'], name='drugtpl_conc_idx'),
        ),
        migrations.AddIndex(
            model_name='drugtemplate',
            index=models.Index(fields=['pharmaceutical_form'], name='drugtpl_form_idx'),
        ),
        migrations.AddIndex(
            model_name='drugtemplate',
            index=models.Index(fields=['is_imported'], name='drugtpl_imported_idx'),
        ),
        migrations.AddIndex(
            model_name='drugtemplate',
            index=models.Index(fields=['import_source'], name='drugtpl_source_idx'),
        ),
        migrations.AddIndex(
            model_name='drugtemplate',
            index=models.Index(fields=['is_imported', 'name'], name='drugtpl_imp_name_idx'),
        ),
        migrations.AddIndex(
            model_name='drugtemplate',
            index=models.Index(fields=['name', 'concentration'], name='drugtpl_name_conc_idx'),
        ),
    ]
