# Generated by Django 6.0.1 on 2026-01-18 23:53

import re
from django.db import migrations


def populate_concentration_and_form(apps, schema_editor):
    """
    Populate concentration and pharmaceutical_form fields from existing presentation data.
    Also mark all existing records as user-created (not imported).
    """
    DrugTemplate = apps.get_model('drugtemplates', 'DrugTemplate')
    
    # Common patterns to extract concentration and form from presentation
    patterns = [
        # "500mg comprimidos" -> concentration: "500 mg", form: "comprimidos"
        (r'(\d+(?:[.,]\d+)?)\s*mg\s+(\w+)', r'\1 mg', r'\2'),
        # "40 mg/mL solução injetável" -> concentration: "40 mg/mL", form: "solução injetável"
        (r'(\d+(?:[.,]\d+)?)\s*mg/mL\s+(.+)', r'\1 mg/mL', r'\2'),
        # "125 mg/mL solução" -> concentration: "125 mg/mL", form: "solução"
        (r'(\d+(?:[.,]\d+)?)\s*mg/ml\s+(.+)', r'\1 mg/mL', r'\2'),
        # "0,1 mg comprimido" -> concentration: "0.1 mg", form: "comprimido" 
        (r'(\d+(?:[.,]\d+)?)\s*mg\s+(\w+)', r'\1 mg', r'\2'),
        # "500mg comprimidos" (no space before mg)
        (r'(\d+(?:[.,]\d+)?)mg\s+(.+)', r'\1 mg', r'\2'),
        # "25.5 mg/mL" without form
        (r'(\d+(?:[.,]\d+)?)\s*mg/mL', r'\1 mg/mL', ''),
        # Just mg without form
        (r'(\d+(?:[.,]\d+)?)\s*mg', r'\1 mg', ''),
    ]
    
    updated_count = 0
    for template in DrugTemplate.objects.all():
        if not template.presentation:
            continue
            
        presentation = template.presentation.strip()
        concentration = ''
        pharmaceutical_form = ''
        
        # Try to parse with regex patterns
        for pattern, conc_template, form_template in patterns:
            match = re.match(pattern, presentation, re.IGNORECASE)
            if match:
                # Extract concentration
                if conc_template:
                    concentration = re.sub(pattern, conc_template, presentation, flags=re.IGNORECASE)
                    # Normalize decimal separator
                    concentration = concentration.replace(',', '.')
                
                # Extract pharmaceutical form
                if form_template and len(match.groups()) >= 2:
                    pharmaceutical_form = match.group(2).strip().lower()
                elif form_template:
                    pharmaceutical_form = re.sub(pattern, form_template, presentation, flags=re.IGNORECASE)
                    pharmaceutical_form = pharmaceutical_form.strip().lower()
                break
        
        # Fallback: if no pattern matched, use the whole presentation as form
        if not concentration and not pharmaceutical_form:
            # Try to split on common words
            words = presentation.lower().split()
            if words:
                # Look for concentration patterns in words
                for i, word in enumerate(words):
                    if 'mg' in word:
                        concentration = word.replace(',', '.')
                        pharmaceutical_form = ' '.join(words[i+1:]) if i+1 < len(words) else ''
                        break
                
                if not concentration:
                    pharmaceutical_form = presentation.lower()
        
        # Clean up extracted values
        if concentration:
            concentration = concentration.strip()
        if pharmaceutical_form:
            pharmaceutical_form = pharmaceutical_form.strip()
        
        # Set defaults if still empty
        if not concentration:
            concentration = 'N/A'
        if not pharmaceutical_form:
            pharmaceutical_form = 'não especificado'
        
        # Update the record
        template.concentration = concentration
        template.pharmaceutical_form = pharmaceutical_form
        template.is_imported = False  # Mark as user-created
        template.save()
        
        updated_count += 1
    
    print(f"Updated {updated_count} DrugTemplate records")


def reverse_populate_concentration_and_form(apps, schema_editor):
    """
    Reverse migration: clear the new fields.
    """
    DrugTemplate = apps.get_model('drugtemplates', 'DrugTemplate')
    DrugTemplate.objects.all().update(
        concentration='',
        pharmaceutical_form='',
        is_imported=False,
        import_source=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('drugtemplates', '0002_refactor_drugtemplate_fields'),
    ]

    operations = [
        migrations.RunPython(
            populate_concentration_and_form,
            reverse_populate_concentration_and_form
        ),
    ]
