# Generated by Django 6.0.1 on 2026-01-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugtemplates', '0003_populate_new_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugtemplate',
            name='presentation',
        ),
    ]
