# Generated by Django 6.0.1 on 2026-01-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugtemplates', '0004_remove_presentation_field_completely'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugtemplate',
            name='concentration',
            field=models.CharField(blank=True, default='', help_text='Concentração do medicamento (ex: 500 mg, 40 mg/mL)', max_length=200, verbose_name='Concentração'),
        ),
        migrations.AlterField(
            model_name='drugtemplate',
            name='pharmaceutical_form',
            field=models.CharField(blank=True, default='', help_text='Forma farmacêutica (ex: comprimido, solução injetável, cápsula)', max_length=200, verbose_name='Forma Farmacêutica'),
        ),
    ]
