# Generated by Django 5.2.1 on 2025-11-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='is_researcher',
            field=models.BooleanField(default=False, help_text='Permite acesso à funcionalidade de pesquisa clínica em evoluções', verbose_name='Pesquisador Clínico'),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='is_researcher',
            field=models.BooleanField(default=False, help_text='Permite acesso à funcionalidade de pesquisa clínica em evoluções', verbose_name='Pesquisador Clínico'),
        ),
    ]
