# Generated by Django 5.2.1 on 2025-06-11 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='hospitals',
            field=models.ManyToManyField(blank=True, help_text='Hospitals this user is a member of', related_name='members', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='last_hospital',
            field=models.ForeignKey(blank=True, help_text='Last hospital context this user was in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_logged_users', to='hospitals.hospital'),
        ),
    ]
