# Generated by Django 5.2.1 on 2025-06-15 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='hospitals',
            field=models.ManyToManyField(blank=True, help_text='Hospitals this user is a member of', related_name='members', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='last_hospital',
            field=models.ForeignKey(blank=True, help_text='Last hospital context this user was in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_logged_users', to='hospitals.hospital'),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
