# Generated by Django 5.2.1 on 2025-08-29 22:53

from django.db import migrations, models


def set_existing_users_password_change_not_required(apps, schema_editor):
    """Set existing users to not require password change."""
    EqmdCustomUser = apps.get_model('accounts', 'EqmdCustomUser')
    # Set all existing users to not require password change
    EqmdCustomUser.objects.all().update(password_change_required=False)


def reverse_set_existing_users_password_change_not_required(apps, schema_editor):
    """Reverse operation - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='password_change_required',
            field=models.BooleanField(default=True, help_text='User must change password before accessing the system'),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='password_change_required',
            field=models.BooleanField(default=True, help_text='User must change password before accessing the system'),
        ),
        # Data migration to set existing users to False
        migrations.RunPython(
            set_existing_users_password_change_not_required,
            reverse_code=reverse_set_existing_users_password_change_not_required,
        ),
    ]
