# Generated by Django 5.2.1 on 2026-01-16 19:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_eqmdcustomuser_is_researcher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matrix_localpart',
            field=models.CharField(blank=True, help_text='Matrix localpart without @ or domain (e.g., joao.silva).', max_length=64, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Matrix localpart must use lowercase letters, numbers, dots, underscores, or hyphens.', regex='^[a-z0-9][a-z0-9._-]{0,63}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matrix_provisioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matrix_provisioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_provisioned_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
