# Generated by Django 5.2.1 on 2025-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_password_change_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User has accepted the terms of use'),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the terms', null=True),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User has accepted the terms of use'),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the user accepted the terms', null=True),
        ),
    ]
