# Generated by Django 6.0.1 on 2026-01-22 00:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_matrix_localpart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ex: Cirurgia Vascular, Cirurgia Geral', max_length=100, unique=True, verbose_name='Nome da Especialidade')),
                ('abbreviation', models.CharField(help_text='Ex: CIRVASC, CIRGER', max_length=10, unique=True, verbose_name='Sigla')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da especialidade', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, help_text='Se desmarcado, esta especialidade não estará disponível para seleção', verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Especialidade Médica',
                'verbose_name_plural': 'Especialidades Médicas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_specialty',
            field=models.ForeignKey(blank=True, help_text='Especialidade selecionada pelo usuário para uso atual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='accounts.medicalspecialty', verbose_name='Especialidade Atual'),
        ),
        migrations.CreateModel(
            name='UserSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False, help_text='Marque como especialidade principal (ex: do residente)', verbose_name='Especialidade Principal')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Atribuída em')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_specialties', to=settings.AUTH_USER_MODEL, verbose_name='Atribuída por')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.medicalspecialty', verbose_name='Especialidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_specialties', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Especialidade do Usuário',
                'verbose_name_plural': 'Especialidades dos Usuários',
                'ordering': ['-is_primary', 'specialty__name'],
                'unique_together': {('user', 'specialty')},
            },
        ),
    ]
