# Generated by Django 5.2.1 on 2025-08-30 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_terms_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, help_text='When user access automatically expires (NULL = no expiration)', null=True),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon (30 days)'), ('expired', 'Access Expired'), ('inactive', 'Inactive (no recent activity)'), ('suspended', 'Administratively Suspended'), ('departed', 'No longer with institution'), ('renewal_required', 'Renewal Required')], db_index=True, default='active', help_text='Current account lifecycle status', max_length=20),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='expected_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Expected duration in months (for residents/students)', null=True),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='expiration_reason',
            field=models.CharField(blank=True, choices=[('end_of_internship', 'End of Internship/Residency'), ('end_of_rotation', 'End of Clinical Rotation'), ('employment_end', 'Employment Termination'), ('leave_of_absence', 'Leave of Absence'), ('administrative', 'Administrative Decision'), ('inactivity', 'Account Inactivity')], help_text='Reason for access expiration', max_length=100),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='expiration_warning_sent',
            field=models.DateTimeField(blank=True, help_text='When expiration warning was last sent', null=True),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='internship_start_date',
            field=models.DateField(blank=True, help_text='Start date for internship/residency (for automatic expiration calculation)', null=True),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='last_meaningful_activity',
            field=models.DateTimeField(blank=True, help_text='Last time user performed meaningful action (not just login)', null=True),
        ),
        migrations.AddField(
            model_name='eqmdcustomuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Direct supervisor for renewal approvals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, help_text='When user access automatically expires (NULL = no expiration)', null=True),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring_soon', 'Expiring Soon (30 days)'), ('expired', 'Access Expired'), ('inactive', 'Inactive (no recent activity)'), ('suspended', 'Administratively Suspended'), ('departed', 'No longer with institution'), ('renewal_required', 'Renewal Required')], db_index=True, default='active', help_text='Current account lifecycle status', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='expected_duration_months',
            field=models.PositiveIntegerField(blank=True, help_text='Expected duration in months (for residents/students)', null=True),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='expiration_reason',
            field=models.CharField(blank=True, choices=[('end_of_internship', 'End of Internship/Residency'), ('end_of_rotation', 'End of Clinical Rotation'), ('employment_end', 'Employment Termination'), ('leave_of_absence', 'Leave of Absence'), ('administrative', 'Administrative Decision'), ('inactivity', 'Account Inactivity')], help_text='Reason for access expiration', max_length=100),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='expiration_warning_sent',
            field=models.DateTimeField(blank=True, help_text='When expiration warning was last sent', null=True),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='internship_start_date',
            field=models.DateField(blank=True, help_text='Start date for internship/residency (for automatic expiration calculation)', null=True),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='last_meaningful_activity',
            field=models.DateTimeField(blank=True, help_text='Last time user performed meaningful action (not just login)', null=True),
        ),
        migrations.AddField(
            model_name='historicaleqmdcustomuser',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Direct supervisor for renewal approvals', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
