# Generated by Django 5.2.1 on 2026-01-30 00:00

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models

import apps.consentforms.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_draft_promoted_at_event_draft_promoted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('markdown_body', models.TextField(verbose_name='Markdown do Termo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consent_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Consentimento',
                'verbose_name_plural': 'Templates de Consentimento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalConsentTemplate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('markdown_body', models.TextField(verbose_name='Markdown do Termo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'historical Template de Consentimento',
                'verbose_name_plural': 'historical Templates de Consentimento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('document_date', models.DateField(verbose_name='Data do Documento')),
                ('procedure_description', models.TextField(verbose_name='Descrição do Procedimento')),
                ('rendered_markdown', models.TextField(verbose_name='Markdown Renderizado')),
                ('rendered_at', models.DateTimeField(verbose_name='Renderizado em')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_forms', to='consentforms.consenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Termo de Consentimento',
                'verbose_name_plural': 'Termos de Consentimento',
                'ordering': ['-event_datetime'],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='ConsentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.consentforms.utils.get_consent_upload_path, verbose_name='Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo')),
                ('mime_type', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('file_type', models.CharField(choices=[('image', 'Imagem'), ('pdf', 'PDF')], max_length=10, verbose_name='Tipo de Arquivo')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consentforms.consentform', verbose_name='Termo de Consentimento')),
            ],
            options={
                'verbose_name': 'Anexo de Consentimento',
                'verbose_name_plural': 'Anexos de Consentimento',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='consenttemplate',
            index=models.Index(fields=['is_active'], name='consent_template_active_idx'),
        ),
    ]
