# Generated by Django 5.2.1 on 2025-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_dashboard_cache',
            },
        ),
        migrations.CreateModel(
            name='WardMappingCache',
            fields=[
                ('cache_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ward_data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_ward_mapping_cache',
            },
        ),
    ]
