# Generated by Django 5.2.1 on 2026-01-12 11:13

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código oficial do procedimento (ex: 0301010012)', max_length=20, unique=True, verbose_name='Código do Procedimento')),
                ('description', models.TextField(help_text='Descrição completa do procedimento', verbose_name='Descrição do Procedimento')),
                ('is_active', models.BooleanField(default=True, help_text='Procedimento disponível para uso', verbose_name='Ativo')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Campo de busca textual (preenchido automaticamente)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Procedimento Médico',
                'verbose_name_plural': 'Procedimentos Médicos',
                'db_table': 'core_medicalprocedure',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active'], name='medicalprocedure_active_idx'), models.Index(fields=['code'], name='medicalprocedure_code_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='medicalprocedure_search_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[0-9A-Za-z]{4,20}$')), name='medicalprocedure_code_format')],
            },
        ),
    ]
