# Generated by Django 5.2.1 on 2026-01-18 00:00

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalprocedure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icd10Code',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Codigo oficial do CID-10 (ex: A00)', max_length=20, unique=True, verbose_name='Codigo ICD-10')),
                ('description', models.TextField(help_text='Descricao completa do CID-10', verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, help_text='Codigo disponivel para uso', verbose_name='Ativo')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, help_text='Campo de busca textual (preenchido automaticamente)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Codigo ICD-10',
                'verbose_name_plural': 'Codigos ICD-10',
                'db_table': 'core_icd10code',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['is_active'], name='icd10code_active_idx'), models.Index(fields=['code'], name='icd10code_code_idx'), django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='icd10code_search_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('code__regex', '^[0-9A-Za-z]{2,20}$')), name='icd10code_code_format')],
            },
        ),
    ]
