# Generated by Django 5.2.1 on 2026-01-12 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixUserBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matrix_id', models.CharField(help_text='Full Matrix ID (e.g., @username:server.com)', max_length=255, unique=True, verbose_name='Matrix User ID')),
                ('verified', models.BooleanField(default=False, help_text='Whether the binding has been verified by the user')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the binding was verified', null=True)),
                ('verification_token', models.CharField(blank=True, help_text='Token for verification process', max_length=64)),
                ('verification_token_expires', models.DateTimeField(blank=True, help_text='When the verification token expires', null=True)),
                ('delegation_enabled', models.BooleanField(default=True, help_text='Whether this binding can be used for bot delegation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_binding', to=settings.AUTH_USER_MODEL, verbose_name='EQMD User')),
            ],
            options={
                'verbose_name': 'Matrix User Binding',
                'verbose_name_plural': 'Matrix User Bindings',
            },
        ),
        migrations.CreateModel(
            name='MatrixBindingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matrix_id', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('event_type', models.CharField(choices=[('created', 'Binding Created'), ('verified', 'Binding Verified'), ('revoked', 'Binding Revoked'), ('delegation_enabled', 'Delegation Enabled'), ('delegation_disabled', 'Delegation Disabled'), ('verification_failed', 'Verification Failed')], max_length=30)),
                ('event_details', models.JSONField(default=dict, help_text='Additional event details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('binding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='botauth.matrixuserbinding')),
            ],
            options={
                'verbose_name': 'Matrix Binding Audit Log',
                'verbose_name_plural': 'Matrix Binding Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='matrixuserbinding',
            index=models.Index(fields=['matrix_id'], name='botauth_mat_matrix__1a80ac_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixuserbinding',
            index=models.Index(fields=['verified', 'delegation_enabled'], name='botauth_mat_verifie_f50eee_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixbindingauditlog',
            index=models.Index(fields=['matrix_id', '-created_at'], name='botauth_mat_matrix__a03c97_idx'),
        ),
        migrations.AddIndex(
            model_name='matrixbindingauditlog',
            index=models.Index(fields=['user_email', '-created_at'], name='botauth_mat_user_em_1050ec_idx'),
        ),
    ]
