# Generated by Django 5.2.1 on 2026-01-12 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botauth', '0001_initial'),
        ('oidc_provider', '0028_alter_client_id_alter_code_id_alter_responsetype_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Human-readable name for this bot', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this bot does')),
                ('allowed_scopes', models.JSONField(default=list, help_text='List of scopes this bot is allowed to request')),
                ('max_delegations_per_hour', models.PositiveIntegerField(default=100, help_text='Maximum delegated tokens this bot can request per hour')),
                ('max_api_calls_per_minute', models.PositiveIntegerField(default=60, help_text='Maximum API calls per minute with delegated tokens')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bot is currently active')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='When this bot was suspended', null=True)),
                ('suspension_reason', models.TextField(blank=True, help_text='Reason for suspension')),
                ('last_delegation_at', models.DateTimeField(blank=True, help_text='Last time this bot requested a delegated token', null=True)),
                ('total_delegations', models.PositiveIntegerField(default=0, help_text='Total number of delegated tokens issued')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_profile', to='oidc_provider.client', verbose_name='OIDC Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Client Profile',
                'verbose_name_plural': 'Bot Client Profiles',
            },
        ),
        migrations.CreateModel(
            name='BotClientAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255)),
                ('bot_name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('created', 'Bot Created'), ('updated', 'Bot Updated'), ('suspended', 'Bot Suspended'), ('reactivated', 'Bot Reactivated'), ('scopes_changed', 'Scopes Changed'), ('secret_rotated', 'Secret Rotated')], max_length=30)),
                ('event_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bot_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='botauth.botclientprofile')),
            ],
            options={
                'verbose_name': 'Bot Client Audit Log',
                'verbose_name_plural': 'Bot Client Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
