# Generated by Django 5.2.1 on 2026-01-12 23:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botauth', '0002_botclientprofile_botclientauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_client_id', models.CharField(max_length=255)),
                ('bot_name', models.CharField(max_length=100)),
                ('matrix_id', models.CharField(max_length=255)),
                ('requested_scopes', models.JSONField(default=list)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('issued', 'Token Issued'), ('denied_inactive', 'Denied: User Inactive'), ('denied_scopes', 'Denied: Invalid Scopes'), ('denied_bot', 'Denied: Bot Suspended'), ('denied_rate', 'Denied: Rate Limited'), ('denied_binding', 'Denied: No Matrix Binding'), ('denied_disabled', 'Denied: Delegation Disabled')], max_length=30)),
                ('granted_scopes', models.JSONField(default=list)),
                ('token_jti', models.CharField(blank=True, max_length=36)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegation_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegation Audit Log',
                'verbose_name_plural': 'Delegation Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='botauth_del_user_id_81a0ce_idx'), models.Index(fields=['bot_client_id', '-created_at'], name='botauth_del_bot_cli_03d3b4_idx'), models.Index(fields=['status', '-created_at'], name='botauth_del_status_ea2e06_idx')],
            },
        ),
    ]
