# Generated by Django 5.2.1 on 2026-01-13 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botauth', '0003_delegationauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('event_id', models.UUIDField(default=None, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(db_index=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('bot_client_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('bot_name', models.CharField(blank=True, max_length=100)),
                ('patient_id', models.UUIDField(db_index=True, null=True)),
                ('event_object_id', models.UUIDField(null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('token_jti', models.CharField(blank=True, max_length=36)),
                ('scopes', models.JSONField(default=list)),
                ('details', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bot Audit Log',
                'verbose_name_plural': 'Bot Audit Logs',
                'ordering': ['-timestamp'],
                'managed': True,
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='botauth_bot_event_t_88df4d_idx'), models.Index(fields=['user_id', '-timestamp'], name='botauth_bot_user_id_1b1f32_idx'), models.Index(fields=['bot_client_id', '-timestamp'], name='botauth_bot_bot_cli_ab8a07_idx'), models.Index(fields=['patient_id', '-timestamp'], name='botauth_bot_patient_9ec3aa_idx')],
            },
        ),
    ]
