# Generated by Django 5.2.1 on 2026-01-13 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botauth', '0004_botauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotDelegationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegation_enabled', models.BooleanField(default=True, help_text='Master switch to enable/disable all bot delegation')),
                ('disabled_at', models.DateTimeField(blank=True, help_text='When delegation was disabled', null=True)),
                ('disabled_reason', models.TextField(blank=True, help_text='Reason for disabling delegation')),
                ('global_rate_limit', models.PositiveIntegerField(default=1000, help_text='Maximum delegations per hour across all bots')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='If True, delegation returns maintenance message')),
                ('maintenance_message', models.TextField(blank=True, default='Bot delegation is temporarily unavailable for maintenance.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disabled_delegation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Delegation Configuration',
                'verbose_name_plural': 'Bot Delegation Configuration',
            },
        ),
    ]
