# Generated by Django 5.2.1 on 2025-08-13 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LGPDComplianceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpo_name', models.CharField(max_length=200, verbose_name='Nome do DPO/Responsável')),
                ('dpo_email', models.EmailField(max_length=254, verbose_name='Email do DPO')),
                ('dpo_phone', models.CharField(max_length=20, verbose_name='Telefone do DPO')),
                ('controller_name', models.CharField(max_length=200, verbose_name='Nome do Controlador')),
                ('controller_address', models.TextField(verbose_name='Endereço do Controlador')),
                ('controller_cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('anpd_notification_threshold', models.IntegerField(default=100, verbose_name='Limite para notificação ANPD (nº pacientes)')),
                ('breach_notification_email', models.EmailField(max_length=254, verbose_name='Email para notificações de incidente')),
                ('default_retention_days', models.IntegerField(default=7300, verbose_name='Período de retenção padrão (dias)')),
                ('deletion_warning_days', models.IntegerField(default=180, verbose_name='Aviso antes da exclusão (dias)')),
                ('privacy_policy_version', models.CharField(default='1.0', max_length=10)),
                ('privacy_policy_last_updated', models.DateField(auto_now=True)),
                ('breach_detection_failed_login_threshold', models.IntegerField(default=10, verbose_name='Limite de tentativas de login falhadas')),
                ('breach_detection_bulk_access_threshold', models.IntegerField(default=50, verbose_name='Limite de acesso em massa a registros')),
                ('breach_detection_off_hours_threshold', models.IntegerField(default=5, verbose_name='Limite de atividade fora do horário')),
                ('breach_detection_geographic_anomaly_km', models.IntegerField(default=100, verbose_name='Limite de distância para anomalia geográfica (km)')),
                ('breach_detection_data_export_threshold', models.IntegerField(default=100, verbose_name='Limite de exportação de dados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Conformidade LGPD',
                'verbose_name_plural': 'Configurações de Conformidade LGPD',
            },
        ),
        migrations.CreateModel(
            name='DataProcessingPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_category', models.CharField(choices=[('patient_identification', 'Identificação do Paciente'), ('patient_contact', 'Contato do Paciente'), ('patient_medical_history', 'Histórico Médico'), ('patient_current_treatment', 'Tratamento Atual'), ('patient_diagnostic_data', 'Dados Diagnósticos'), ('staff_identification', 'Identificação da Equipe'), ('staff_professional', 'Dados Profissionais'), ('system_audit', 'Auditoria do Sistema'), ('communication_logs', 'Logs de Comunicação')], max_length=50)),
                ('purpose', models.CharField(choices=[('medical_care', 'Prestação de cuidados médicos'), ('legal_obligation', 'Cumprimento de obrigação legal'), ('legitimate_interest', 'Interesse legítimo'), ('consent', 'Consentimento do titular'), ('vital_interest', 'Proteção da vida')], max_length=50)),
                ('legal_basis', models.CharField(choices=[('art7_i', 'Art. 7º, I - Consentimento do titular'), ('art7_ii', 'Art. 7º, II - Cumprimento de obrigação legal ou regulatória'), ('art7_iii', 'Art. 7º, III - Execução de políticas públicas'), ('art7_iv', 'Art. 7º, IV - Realização de estudos por órgão de pesquisa'), ('art7_v', 'Art. 7º, V - Execução de contrato'), ('art7_vi', 'Art. 7º, VI - Exercício regular de direitos (interesse legítimo)'), ('art7_vii', 'Art. 7º, VII - Proteção da vida ou incolumidade física'), ('art7_viii', 'Art. 7º, VIII - Tutela da saúde'), ('art7_ix', 'Art. 7º, IX - Interesse legítimo do controlador'), ('art7_x', 'Art. 7º, X - Proteção do crédito'), ('art11_ii_a', 'Art. 11º, II, a - Procedimentos médicos/saúde'), ('art11_ii_b', 'Art. 11º, II, b - Saúde pública'), ('art11_ii_c', 'Art. 11º, II, c - Estudos por órgão de pesquisa'), ('art11_ii_d', 'Art. 11º, II, d - Exercício regular de direitos'), ('art11_ii_e', 'Art. 11º, II, e - Proteção da vida'), ('art11_ii_f', 'Art. 11º, II, f - Tutela da saúde'), ('art11_ii_g', 'Art. 11º, II, g - Garantia da prevenção à fraude')], max_length=20)),
                ('description', models.TextField(help_text='Descrição detalhada do processamento')),
                ('data_fields_included', models.TextField(help_text='Campos de dados incluídos (JSON)')),
                ('processing_activities', models.TextField(help_text='Atividades de processamento realizadas')),
                ('data_recipients', models.TextField(blank=True, help_text='Quem recebe os dados')),
                ('international_transfers', models.BooleanField(default=False)),
                ('transfer_safeguards', models.TextField(blank=True, help_text='Salvaguardas para transferências')),
                ('retention_period_days', models.IntegerField()),
                ('retention_criteria', models.TextField(help_text='Critérios para retenção')),
                ('security_measures', models.TextField(help_text='Medidas de segurança implementadas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finalidade de Processamento de Dados',
                'verbose_name_plural': 'Finalidades de Processamento de Dados',
                'ordering': ['data_category', 'purpose'],
            },
        ),
    ]
