# Generated by Django 5.2.1 on 2025-08-13 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_add_lgpd_compliance_models'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDataRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('access', 'Acesso aos dados (Art. 18, I e II)'), ('correction', 'Correção de dados (Art. 18, III)'), ('deletion', 'Exclusão de dados (Art. 18, IV)'), ('portability', 'Portabilidade de dados (Art. 18, V)'), ('objection', 'Oposição ao tratamento (Art. 18, § 2º)'), ('consent_revocation', 'Revogação de Consentimento (Art. 8, § 5º / Art. 18, IX)'), ('consent_update', 'Atualização de Consentimento'), ('information', 'Informações sobre compartilhamento (Art. 18, VII)')], max_length=20)),
                ('description', models.TextField(verbose_name='Descrição da solicitação')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('under_review', 'Em análise'), ('identity_verification', 'Verificação de identidade'), ('approved', 'Aprovado'), ('in_progress', 'Em andamento'), ('completed', 'Concluído'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='pending', max_length=25)),
                ('requester_name', models.CharField(max_length=200, verbose_name='Nome do solicitante')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='Email para contato')),
                ('requester_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('requester_relationship', models.CharField(choices=[('self', 'Próprio paciente'), ('parent', 'Pai/Mãe'), ('guardian', 'Responsável legal'), ('attorney', 'Procurador'), ('heir', 'Herdeiro')], default='self', max_length=50, verbose_name='Relação com o paciente')),
                ('patient_name_provided', models.CharField(max_length=200, verbose_name='Nome do paciente informado')),
                ('patient_cpf_provided', models.CharField(blank=True, max_length=14, verbose_name='CPF informado')),
                ('patient_birth_date_provided', models.DateField(blank=True, null=True, verbose_name='Data nascimento informada')),
                ('additional_identifiers', models.TextField(blank=True, verbose_name='Outros identificadores')),
                ('identity_document', models.FileField(blank=True, null=True, upload_to='lgpd/identity_docs/', verbose_name='Documento de identidade (digitalizado pela equipe)')),
                ('authorization_document', models.FileField(blank=True, null=True, upload_to='lgpd/authorization_docs/', verbose_name='Procuração/autorização (se aplicável)')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(editable=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, verbose_name='Notas da resposta')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da rejeição')),
                ('response_sent_at', models.DateTimeField(blank=True, null=True)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='lgpd/responses/', verbose_name='Arquivo de resposta')),
                ('data_export_format', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Formato de exportação')),
                ('legal_basis_for_rejection', models.CharField(blank=True, max_length=100)),
                ('anpd_notification_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_data_requests', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo atendimento')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_data_requests', to=settings.AUTH_USER_MODEL, verbose_name='Criado por (funcionário)')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_requests', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_data_requests', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
            ],
            options={
                'verbose_name': 'Solicitação de Direitos do Titular',
                'verbose_name_plural': 'Solicitações de Direitos dos Titulares',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataCorrectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Campo a corrigir')),
                ('current_value', models.TextField(verbose_name='Valor atual')),
                ('requested_value', models.TextField(verbose_name='Valor solicitado')),
                ('justification', models.TextField(verbose_name='Justificativa para correção')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name='Notas da revisão')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('correction_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_corrections', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_details', to='compliance.patientdatarequest')),
            ],
            options={
                'verbose_name': 'Detalhe de Correção',
                'verbose_name_plural': 'Detalhes de Correção',
            },
        ),
        migrations.AddIndex(
            model_name='patientdatarequest',
            index=models.Index(fields=['status', 'due_date'], name='compliance__status_ae807c_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdatarequest',
            index=models.Index(fields=['patient', 'request_type'], name='compliance__patient_56d81e_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdatarequest',
            index=models.Index(fields=['requester_email', 'requested_at'], name='compliance__request_9111da_idx'),
        ),
    ]
