# Generated by Django 5.2.1 on 2025-08-14 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_add_patient_data_request_models'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.CharField(max_length=50, unique=True)),
                ('context', models.CharField(choices=[('patient_registration', 'Cadastro de Paciente'), ('medical_consultation', 'Consulta Médica'), ('emergency_treatment', 'Atendimento de Emergência'), ('staff_onboarding', 'Integração de Funcionário'), ('research_participation', 'Participação em Pesquisa'), ('photo_video_capture', 'Captura de Foto/Vídeo'), ('prescription_management', 'Gestão de Prescrições')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('purpose_description', models.TextField(verbose_name='Descrição da finalidade')),
                ('data_categories', models.TextField(verbose_name='Categorias de dados coletados')),
                ('legal_basis', models.CharField(max_length=100, verbose_name='Base legal')),
                ('retention_period', models.CharField(max_length=200, verbose_name='Período de retenção')),
                ('recipients', models.TextField(verbose_name='Destinatários dos dados')),
                ('rights_summary', models.TextField(verbose_name='Resumo dos direitos do titular')),
                ('contact_info', models.TextField(verbose_name='Informações de contato DPO')),
                ('display_format', models.CharField(choices=[('modal', 'Modal/Pop-up'), ('inline', 'Integrado na página'), ('banner', 'Banner de notificação'), ('pdf', 'Documento PDF')], default='modal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aviso de Processamento de Dados',
                'verbose_name_plural': 'Avisos de Processamento de Dados',
                'ordering': ['context', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_type', models.CharField(choices=[('data_processing', 'Processamento de Dados Gerais'), ('medical_treatment', 'Tratamento Médico'), ('photo_video', 'Captura de Foto/Vídeo'), ('research', 'Pesquisa Médica'), ('marketing', 'Comunicações de Marketing'), ('data_sharing', 'Compartilhamento de Dados'), ('hospital_consent', 'Consentimento Hospitalar')], max_length=30)),
                ('purpose_description', models.TextField(verbose_name='Finalidade específica')),
                ('data_categories', models.TextField(verbose_name='Categorias de dados envolvidos')),
                ('processing_activities', models.TextField(verbose_name='Atividades de processamento')),
                ('status', models.CharField(choices=[('granted', 'Consentimento Concedido'), ('denied', 'Consentimento Negado'), ('withdrawn', 'Consentimento Retirado'), ('expired', 'Consentimento Expirado')], default='granted', max_length=20)),
                ('granted_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.CharField(max_length=200, verbose_name='Concedido por')),
                ('granted_by_relationship', models.CharField(choices=[('self', 'Próprio paciente'), ('parent', 'Pai/Mãe'), ('guardian', 'Responsável legal'), ('healthcare_proxy', 'Procurador de saúde')], default='self', max_length=50)),
                ('consent_method', models.CharField(choices=[('web_form', 'Formulário Web'), ('verbal', 'Verbal (registrado)'), ('paper_form', 'Formulário Físico'), ('electronic_signature', 'Assinatura Eletrônica')], default='web_form', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('legal_basis', models.CharField(max_length=100)),
                ('lawful_basis_explanation', models.TextField(verbose_name='Explicação da base legal')),
                ('consent_source', models.CharField(choices=[('direct', 'Consentimento Direto'), ('hospital_form', 'Formulário Hospitalar'), ('supplementary', 'Consentimento Suplementar')], default='direct', help_text='Origem do consentimento', max_length=20)),
                ('hospital_consent_reference', models.CharField(blank=True, help_text='Referência do consentimento hospitalar (número do documento)', max_length=100)),
                ('consent_evidence', models.FileField(blank=True, help_text='Documento comprobatório do consentimento (PDF escaneado do hospital)', null=True, upload_to='consent_evidence/')),
                ('hospital_consent_document', models.FileField(blank=True, help_text='Cópia escaneada do consentimento hospitalar', null=True, upload_to='hospital_consent/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Registro de Consentimento',
                'verbose_name_plural': 'Registros de Consentimento',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawn_by', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('withdrawn_at', models.DateTimeField(auto_now_add=True)),
                ('data_deleted', models.BooleanField(default=False)),
                ('data_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_evidence', models.TextField(blank=True)),
                ('consent_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='compliance.consentrecord')),
            ],
            options={
                'verbose_name': 'Retirada de Consentimento',
                'verbose_name_plural': 'Retiradas de Consentimento',
            },
        ),
        migrations.CreateModel(
            name='MinorConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_birth_date', models.DateField()),
                ('age_at_consent', models.IntegerField()),
                ('is_minor', models.BooleanField(default=True)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_relationship', models.CharField(choices=[('mother', 'Mãe'), ('father', 'Pai'), ('legal_guardian', 'Responsável Legal'), ('court_appointed', 'Designado pelo Tribunal')], max_length=30)),
                ('guardian_document', models.CharField(help_text='CPF do responsável', max_length=20)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('consent_date', models.DateTimeField()),
                ('consent_method', models.CharField(choices=[('in_person', 'Presencial'), ('electronic', 'Eletrônico'), ('phone_verified', 'Telefone (verificado)')], max_length=30)),
                ('guardian_id_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, max_length=100)),
                ('consent_document', models.FileField(blank=True, null=True, upload_to='minor_consent/')),
                ('data_sharing_restricted', models.BooleanField(default=True)),
                ('marketing_prohibited', models.BooleanField(default=True)),
                ('research_participation_allowed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minor_consent', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Consentimento de Menor',
                'verbose_name_plural': 'Consentimentos de Menores',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('policy_type', models.CharField(choices=[('main', 'Política Principal'), ('staff', 'Política para Funcionários'), ('research', 'Política para Pesquisa'), ('marketing', 'Política para Marketing')], default='main', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Resumo executivo da política')),
                ('content_markdown', models.TextField(help_text='Conteúdo completo em Markdown')),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('legal_review_completed', models.BooleanField(default=False)),
                ('legal_review_date', models.DateTimeField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('legal_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Política de Privacidade',
                'verbose_name_plural': 'Políticas de Privacidade',
                'ordering': ['-effective_date', '-version'],
            },
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['patient', 'consent_type', 'status'], name='compliance__patient_63bee7_idx'),
        ),
        migrations.AddIndex(
            model_name='consentrecord',
            index=models.Index(fields=['granted_at', 'status'], name='compliance__granted_3f39f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privacypolicy',
            unique_together={('version', 'policy_type')},
        ),
    ]
