# Generated by Django 5.2.1 on 2025-08-14 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_add_data_lifecycle_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('data_breach', 'Violação de Dados'), ('unauthorized_access', 'Acesso Não Autorizado'), ('data_loss', 'Perda de Dados'), ('system_intrusion', 'Intrusão no Sistema'), ('malware_attack', 'Ataque de Malware'), ('phishing_attack', 'Ataque de Phishing'), ('insider_threat', 'Ameaça Interna'), ('physical_security', 'Segurança Física'), ('data_corruption', 'Corrupção de Dados'), ('service_disruption', 'Interrupção de Serviço'), ('configuration_error', 'Erro de Configuração'), ('human_error', 'Erro Humano')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('critical', 'Crítica')], max_length=10)),
                ('status', models.CharField(choices=[('detected', 'Detectado'), ('investigating', 'Em Investigação'), ('contained', 'Contido'), ('eradicated', 'Erradicado'), ('recovering', 'Em Recuperação'), ('resolved', 'Resolvido'), ('closed', 'Fechado')], default='detected', max_length=15)),
                ('detected_at', models.DateTimeField()),
                ('detection_method', models.CharField(choices=[('automated_monitoring', 'Monitoramento Automatizado'), ('user_report', 'Relatório de Usuário'), ('security_audit', 'Auditoria de Segurança'), ('external_notification', 'Notificação Externa'), ('routine_inspection', 'Inspeção de Rotina'), ('third_party_alert', 'Alerta de Terceiros')], max_length=50)),
                ('description', models.TextField()),
                ('initial_assessment', models.TextField(blank=True)),
                ('affected_systems', models.TextField(default=list, help_text='JSON list of affected systems')),
                ('affected_data_categories', models.TextField(default=list, help_text='JSON list of affected data categories')),
                ('estimated_records_affected', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('minimal', 'Mínimo'), ('low', 'Baixo'), ('moderate', 'Moderado'), ('high', 'Alto'), ('severe', 'Severo')], default='low', max_length=10)),
                ('risk_assessment_notes', models.TextField(blank=True)),
                ('potential_impact', models.TextField(blank=True)),
                ('containment_at', models.DateTimeField(blank=True, null=True)),
                ('eradication_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_at', models.DateTimeField(blank=True, null=True)),
                ('anpd_notification_required', models.BooleanField(default=False)),
                ('data_subject_notification_required', models.BooleanField(default=False)),
                ('anpd_notification_deadline', models.DateTimeField(blank=True, null=True)),
                ('subject_notification_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_incidents', to=settings.AUTH_USER_MODEL)),
                ('incident_commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_incidents', to=settings.AUTH_USER_MODEL)),
                ('response_team', models.ManyToManyField(blank=True, related_name='incident_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente de Segurança',
                'verbose_name_plural': 'Incidentes de Segurança',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('log_file', 'Arquivo de Log'), ('screenshot', 'Captura de Tela'), ('network_capture', 'Captura de Rede'), ('file_sample', 'Amostra de Arquivo'), ('email_header', 'Cabeçalho de Email'), ('system_dump', 'Dump de Sistema'), ('database_record', 'Registro de Banco'), ('witness_statement', 'Declaração de Testemunha'), ('external_report', 'Relatório Externo'), ('forensic_image', 'Imagem Forense')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='incident_evidence/')),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('collection_method', models.CharField(max_length=100)),
                ('integrity_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, max_length=100)),
                ('attorney_client_privileged', models.BooleanField(default=False)),
                ('retention_required', models.BooleanField(default=True)),
                ('retention_deadline', models.DateTimeField(blank=True, null=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='compliance.securityincident')),
            ],
            options={
                'verbose_name': 'Evidência de Incidente',
                'verbose_name_plural': 'Evidências de Incidente',
                'ordering': ['collected_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('investigation', 'Investigação'), ('containment', 'Contenção'), ('eradication', 'Erradicação'), ('recovery', 'Recuperação'), ('communication', 'Comunicação'), ('documentation', 'Documentação'), ('evidence_collection', 'Coleta de Evidências'), ('system_change', 'Alteração de Sistema'), ('notification', 'Notificação'), ('training', 'Treinamento')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('performed_at', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('results', models.TextField(blank=True)),
                ('evidence_collected', models.TextField(blank=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_deadline', models.DateTimeField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='compliance.securityincident')),
            ],
            options={
                'verbose_name': 'Ação de Resposta',
                'verbose_name_plural': 'Ações de Resposta',
                'ordering': ['performed_at'],
            },
        ),
        migrations.CreateModel(
            name='BreachNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('notification_type', models.CharField(choices=[('anpd', 'ANPD (Autoridade Nacional)'), ('data_subject', 'Titular dos Dados'), ('regulatory_authority', 'Autoridade Regulatória'), ('law_enforcement', 'Autoridades Policiais'), ('business_partner', 'Parceiro de Negócios'), ('media', 'Mídia'), ('public_notice', 'Aviso Público')], max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_contact', models.CharField(max_length=200)),
                ('delivery_method', models.CharField(choices=[('email', 'Email'), ('postal_mail', 'Correio'), ('web_portal', 'Portal Web'), ('phone_call', 'Ligação Telefônica'), ('in_person', 'Presencial'), ('public_notice', 'Aviso Público'), ('media_release', 'Comunicado à Imprensa')], max_length=15)),
                ('subject', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('attachments', models.TextField(blank=True, help_text='JSON list of attachment files')),
                ('scheduled_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('drafted', 'Rascunho Preparado'), ('reviewed', 'Revisado'), ('sent', 'Enviado'), ('acknowledged', 'Confirmado'), ('failed', 'Falhou')], default='pending', max_length=15)),
                ('delivery_confirmation', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('legal_basis', models.CharField(max_length=100)),
                ('compliance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='compliance.securityincident')),
            ],
            options={
                'verbose_name': 'Notificação de Violação',
                'verbose_name_plural': 'Notificações de Violação',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['status', 'severity'], name='compliance__status_0cafb8_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['detected_at', 'incident_type'], name='compliance__detecte_16cb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['anpd_notification_required', 'anpd_notification_deadline'], name='compliance__anpd_no_3051e4_idx'),
        ),
    ]
