# Generated by Django 5.2.1 on 2025-11-09 20:16

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailynotes', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailynote',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='dailynote',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='dailynote_search_gin_idx'),
        ),
    ]
