# Generated by Django 5.2.1 on 2025-07-20 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('color', models.CharField(default='#007bff', help_text='Cor em formato hexadecimal (ex: #007bff)', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag Permitida',
                'verbose_name_plural': 'Tags Permitidas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_instances', to='patients.allowedtag', verbose_name='Tag Permitida')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('healthcard_number', models.CharField(blank=True, max_length=30, verbose_name='Número do Cartão de Saúde')),
                ('id_number', models.CharField(blank=True, max_length=30, verbose_name='Número de Identidade')),
                ('fiscal_number', models.CharField(blank=True, max_length=30, verbose_name='Número Fiscal')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado/Província')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('status', models.IntegerField(choices=[(1, 'Ambulatorial'), (2, 'Internado'), (3, 'Emergência'), (4, 'Alta'), (5, 'Transferido')], default=1, verbose_name='Status')),
                ('bed', models.CharField(blank=True, max_length=20, verbose_name='Leito/Cama')),
                ('last_admission_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Admissão')),
                ('last_discharge_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Alta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='patients', to='patients.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
    ]
