# Generated by Django 5.2.1 on 2025-06-08 13:51

import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('hospitals', '0003_hospital_created_at_hospital_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='UUIDTaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='object ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_tagged_items', to='contenttypes.contenttype', verbose_name='content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='patients.allowedtag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('healthcard_number', models.CharField(blank=True, max_length=30, verbose_name='Número do Cartão de Saúde')),
                ('id_number', models.CharField(blank=True, max_length=30, verbose_name='Número de Identidade')),
                ('fiscal_number', models.CharField(blank=True, max_length=30, verbose_name='Número Fiscal')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado/Província')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('status', models.IntegerField(choices=[(1, 'Outpatient'), (2, 'Inpatient'), (3, 'Emergency'), (4, 'Discharged'), (5, 'Transferred')], default=1, verbose_name='Status')),
                ('bed', models.CharField(blank=True, max_length=20, verbose_name='Leito/Cama')),
                ('last_admission_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Admissão')),
                ('last_discharge_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Alta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_patients', to='hospitals.hospital', verbose_name='Hospital Atual')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='patients.UUIDTaggedItem', to='patients.AllowedTag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientHospitalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_number', models.CharField(max_length=30, verbose_name='Número de Registro')),
                ('first_admission_date', models.DateField(blank=True, null=True, verbose_name='Data da Primeira Admissão')),
                ('last_admission_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Admissão')),
                ('last_discharge_date', models.DateField(blank=True, null=True, verbose_name='Data da Última Alta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_records', to='hospitals.hospital', verbose_name='Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_records', to='patients.patient', verbose_name='Paciente')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hospital Record',
                'verbose_name_plural': 'Hospital Records',
                'indexes': [models.Index(fields=['patient', 'hospital'], name='patients_pa_patient_952f92_idx'), models.Index(fields=['hospital', 'record_number'], name='patients_pa_hospita_dbed8d_idx')],
                'unique_together': {('patient', 'hospital')},
            },
        ),
    ]
