# Generated by Django 5.2.1 on 2025-10-14 18:57

from django.db import migrations


def update_discharged_patients_to_outpatient(apps, schema_editor):
    """
    Update existing patients with status=DISCHARGED to status=OUTPATIENT
    and clear their ward field.

    This reflects the semantic change where discharge means becoming an outpatient,
    not a separate terminal status.
    """
    Patient = apps.get_model('patients', 'Patient')

    # DISCHARGED = 4, OUTPATIENT = 1
    discharged_patients = Patient.objects.filter(status=4)

    count = discharged_patients.count()
    if count > 0:
        # Update status to OUTPATIENT and clear ward
        discharged_patients.update(status=1, ward=None)
        print(f"Updated {count} discharged patients to outpatient status with cleared ward")
    else:
        print("No discharged patients found to update")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by setting outpatient patients back to discharged.
    Note: This is a best-effort reversal and may not be perfect since we can't
    distinguish between originally outpatient and originally discharged patients.
    """
    # Since we can't reliably reverse this, we'll just pass
    # The forward migration is a semantic correction, not a data structure change
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            update_discharged_patients_to_outpatient,
            reverse_migration
        ),
    ]
