# Generated by Django 5.2.1 on 2025-08-14 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='data_completeness_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='deletion_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='last_data_audit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='last_interaction_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='protection_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='protection_applied_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='protection_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='retention_category',
            field=models.CharField(choices=[('active_treatment', 'Tratamento Ativo'), ('follow_up', 'Acompanhamento'), ('discharged', 'Alta Médica'), ('transferred', 'Transferido'), ('deceased', 'Óbito')], default='active_treatment', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='data_completeness_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='patient',
            name='deletion_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_data_audit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_interaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='protection_applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='protection_applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protected_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='protection_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='retention_category',
            field=models.CharField(choices=[('active_treatment', 'Tratamento Ativo'), ('follow_up', 'Acompanhamento'), ('discharged', 'Alta Médica'), ('transferred', 'Transferido'), ('deceased', 'Óbito')], default='active_treatment', max_length=30),
        ),
    ]
