# Generated by Django 5.2.1 on 2025-08-25 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status', 'ward'], name='patients_pa_status_c1872c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='patients_pa_name_8d04ea_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['current_record_number'], name='patients_pa_current_42513c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['current_admission_id'], name='patients_pa_current_de4ba7_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_admission_date'], name='patients_pa_last_ad_310c23_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_discharge_date'], name='patients_pa_last_di_bcd9ac_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['patient', 'admission_datetime'], name='patients_pa_patient_71b1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['ward', 'admission_datetime'], name='patients_pa_ward_id_97e571_idx'),
        ),
        migrations.AddIndex(
            model_name='ward',
            index=models.Index(fields=['is_active', 'name'], name='patients_wa_is_acti_a8dc87_idx'),
        ),
    ]
