# Generated by Django 5.2.1 on 2025-06-08 13:54

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_uuidtaggeditem_id'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uuidtaggeditem',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='uuidtaggeditem',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='patient',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.DeleteModel(
            name='AllowedTag',
        ),
        migrations.DeleteModel(
            name='UUIDTaggedItem',
        ),
    ]
