# Generated by Django 5.2.1 on 2025-06-08 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_uuidtaggeditem_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='tags',
        ),
    ]
