# Generated by Django 5.2.1 on 2025-07-27 23:49

import apps.outpatientprescriptions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugtemplates', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutpatientPrescription',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instruções')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('finalized', 'Finalizada')], default='draft', max_length=20, verbose_name='Status')),
                ('prescription_date', models.DateField(default=apps.outpatientprescriptions.models.get_current_date, verbose_name='Data da Receita')),
            ],
            options={
                'verbose_name': 'Receita Ambulatorial',
                'verbose_name_plural': 'Receitas Ambulatoriais',
                'ordering': ['-prescription_date', '-event_datetime'],
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200, verbose_name='Nome do Medicamento')),
                ('presentation', models.CharField(max_length=300, verbose_name='Apresentação')),
                ('usage_instructions', models.TextField(verbose_name='Instruções de Uso')),
                ('quantity', models.CharField(max_length=100, verbose_name='Quantidade')),
                ('order', models.PositiveIntegerField(help_text='Ordem de exibição do item na receita', verbose_name='Ordem')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outpatientprescriptions.outpatientprescription', verbose_name='Receita')),
                ('source_template', models.ForeignKey(blank=True, help_text='Template de medicamento usado como base para este item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugtemplates.drugtemplate', verbose_name='Template Origem')),
            ],
            options={
                'verbose_name': 'Item da Receita',
                'verbose_name_plural': 'Itens da Receita',
                'ordering': ['order'],
            },
        ),
    ]
