# Generated by Django 5.2.1 on 2025-07-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatientprescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatientprescription',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instruções gerais da receita', null=True, verbose_name='Instruções'),
        ),
    ]
