# Generated by Django 5.2.1 on 2025-07-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpatientprescriptions', '0002_alter_outpatientprescription_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpatientprescription',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instruções'),
        ),
    ]
