# Generated by Django 5.2.1 on 2025-08-01 12:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Formulário')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('pdf_file', models.FileField(upload_to='pdf_forms/templates/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Arquivo PDF')),
                ('form_fields', models.JSONField(blank=True, default=dict, help_text='JSON configuration with field positions and properties', verbose_name='Configuração dos Campos')),
                ('hospital_specific', models.BooleanField(default=True, verbose_name='Específico do Hospital')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pdf_form_templates_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pdf_form_templates_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Template de Formulário PDF',
                'verbose_name_plural': 'Templates de Formulários PDF',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PDFFormSubmission',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('form_data', models.JSONField(verbose_name='Dados do Formulário')),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pdf_forms.pdfformtemplate', verbose_name='Template do Formulário')),
            ],
            options={
                'verbose_name': 'Submissão de Formulário PDF',
                'verbose_name_plural': 'Submissões de Formulários PDF',
            },
            bases=('events.event',),
        ),
        migrations.AddIndex(
            model_name='pdfformtemplate',
            index=models.Index(fields=['is_active'], name='pdf_form_template_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfformtemplate',
            index=models.Index(fields=['hospital_specific'], name='pdf_form_template_hospital_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfformsubmission',
            index=models.Index(fields=['form_template'], name='pdf_submission_template_idx'),
        ),
    ]
