# Generated by Django 5.2.1 on 2026-01-12 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfformtemplate',
            name='form_type',
            field=models.CharField(choices=[('HOSPITAL', 'Hospital Specific'), ('APAC', 'APAC National'), ('AIH', 'AIH National')], default='HOSPITAL', max_length=20, verbose_name='Tipo de Formulário'),
        ),
        migrations.AddIndex(
            model_name='pdfformtemplate',
            index=models.Index(fields=['form_type'], name='pdf_form_template_type_idx'),
        ),
    ]
