# Generated by Django 6.0.4 on 2026-06-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_forms', '0002_pdfformtemplate_form_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfformtemplate',
            name='allow_duplication',
            field=models.BooleanField(default=False, help_text='Quando ativo, permite que usuários autorizados criem cópias de submissões deste template.', verbose_name='Permitir duplicação'),
        ),
    ]
