# Generated by Django 6.0.1 on 2026-02-01 10:57

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_type_and_more'),
        ('patients', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReport',
            fields=[
                ('event_ptr', models.ForeignKey(auto_created=True, blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, parent_link=True, related_name='+', to='events.event')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'Anamnese e Exame Físico'), (1, 'Evolução'), (2, 'Nota/Observação'), (3, 'Imagem'), (4, 'Resultado de Exame'), (5, 'Requisição de Exame'), (6, 'Relatório de Alta'), (7, 'Receita'), (8, 'Relatório'), (9, 'Série de Fotos'), (10, 'Vídeo Curto'), (11, 'Formulário PDF'), (12, 'Alteração de Prontuário'), (13, 'Admissão Hospitalar'), (14, 'Alta Hospitalar'), (15, 'Alteração de Status'), (16, 'Admissão de Emergência'), (17, 'Transferência'), (18, 'Declaração de Óbito'), (19, 'Status Ambulatorial'), (20, 'Tag Adicionada'), (21, 'Tag Removida'), (22, 'Tags Removidas em Lote'), (23, 'Termo de Consentimento')], verbose_name='Tipo de Evento')),
                ('event_datetime', models.DateTimeField(verbose_name='Data e Hora do Evento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_draft', models.BooleanField(default=False, help_text='Indica se este evento é um rascunho criado por bot', verbose_name='É Rascunho')),
                ('draft_created_by_bot', models.CharField(blank=True, help_text='Client ID do bot que criou o rascunho', max_length=255, verbose_name='Criado por Bot')),
                ('draft_expires_at', models.DateTimeField(blank=True, help_text='Quando o rascunho expira automaticamente', null=True, verbose_name='Expira em')),
                ('draft_promoted_at', models.DateTimeField(blank=True, help_text='Data/hora em que o rascunho foi promovido a definitivo', null=True, verbose_name='Promovido em')),
                ('content', models.TextField(verbose_name='Content')),
                ('document_date', models.DateField(verbose_name='Document Date')),
                ('title', models.CharField(blank=True, help_text='Optional title for the report', max_length=255, verbose_name='Title')),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('draft_delegated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que delegou permissão ao bot', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Delegado por')),
                ('draft_promoted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Usuário que promoveu este rascunho a definitivo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Promovido por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.patient', verbose_name='Paciente')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, help_text='Template used to create this report (null if manual creation)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.reporttemplate', verbose_name='Template')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'historical Report',
                'verbose_name_plural': 'historical Reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('content', models.TextField(verbose_name='Content')),
                ('document_date', models.DateField(verbose_name='Document Date')),
                ('title', models.CharField(blank=True, help_text='Optional title for the report', max_length=255, verbose_name='Title')),
                ('template', models.ForeignKey(blank=True, help_text='Template used to create this report (null if manual creation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-event_datetime'],
            },
            bases=('events.event',),
        ),
    ]
