# Generated by Django 5.2.1 on 2025-06-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAndPhysical',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('content', models.TextField(verbose_name='Conteúdo')),
            ],
            options={
                'verbose_name': 'Anamnese e Exame Físico',
                'verbose_name_plural': 'Anamneses e Exames Físicos',
                'ordering': ['-event_datetime'],
            },
            bases=('events.event',),
        ),
    ]
