# Generated by Django 5.2.1 on 2025-06-28 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoseriesfile',
            options={'ordering': ['order']},
        ),
        migrations.RemoveIndex(
            model_name='photoseriesfile',
            name='photoseries_file_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='photoseriesfile',
            name='photoseries_file_media_idx',
        ),
        migrations.AlterUniqueTogether(
            name='photoseriesfile',
            unique_together={('photo_series', 'order')},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='photoseries',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='file_id',
            field=models.CharField(blank=True, help_text='FilePond file identifier', max_length=100, null=True, verbose_name='File ID'),
        ),
        migrations.AddField(
            model_name='photo',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo'),
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='photo',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original'),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Caminho da Miniatura'),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura'),
        ),
        migrations.AddField(
            model_name='photoseriesfile',
            name='file_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='File ID'),
        ),
        migrations.AddField(
            model_name='photoseriesfile',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoseriesfile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photoseriesfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='photoseriesfile',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='photoseriesfile',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Legenda'),
        ),
        migrations.AlterField(
            model_name='photoseries',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Legenda da Série'),
        ),
        migrations.AlterField(
            model_name='photoseriesfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photoseriesfile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photoseriesfile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='photoseriesfile',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoseriesfile',
            name='photo_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediafiles.photoseries', verbose_name='Série de Fotos'),
        ),
        migrations.RemoveField(
            model_name='photoseriesfile',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='photoseriesfile',
            name='updated_at',
        ),
    ]
