# Generated by Django 5.2.1 on 2025-06-22 01:38

import apps.mediafiles.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Generated thumbnail image', null=True, upload_to=apps.mediafiles.utils.get_thumbnail_upload_path, verbose_name='Miniatura'),
        ),
    ]
