# Generated by Django 5.2.1 on 2025-06-23 18:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type'),
        ('mediafiles', '0003_migrate_existing_thumbnails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSeries',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('caption', models.TextField(blank=True, help_text='Optional caption for the photo series', verbose_name='Legenda')),
            ],
            options={
                'verbose_name': 'Série de Fotos',
                'verbose_name_plural': 'Séries de Fotos',
            },
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='PhotoSeriesFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the photo series file', primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Order of the photo in the series', verbose_name='Ordem')),
                ('description', models.TextField(blank=True, help_text='Optional description for this specific photo', verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('media_file', models.ForeignKey(help_text='The media file in this series', on_delete=django.db.models.deletion.CASCADE, to='mediafiles.mediafile', verbose_name='Arquivo de Mídia')),
                ('photo_series', models.ForeignKey(help_text='The photo series this file belongs to', on_delete=django.db.models.deletion.CASCADE, to='mediafiles.photoseries', verbose_name='Série de Fotos')),
            ],
            options={
                'verbose_name': 'Arquivo da Série de Fotos',
                'verbose_name_plural': 'Arquivos da Série de Fotos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='photoseries',
            name='photos',
            field=models.ManyToManyField(help_text='Photos in this series', through='mediafiles.PhotoSeriesFile', to='mediafiles.mediafile', verbose_name='Fotos'),
        ),
        migrations.AddIndex(
            model_name='photoseriesfile',
            index=models.Index(fields=['photo_series', 'order'], name='photoseries_file_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='photoseriesfile',
            unique_together={('photo_series', 'order')},
        ),
    ]
