# Generated by Django 5.2.1 on 2025-06-23 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_type'),
        ('mediafiles', '0004_photoseries_photoseriesfile_photoseries_photos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('caption', models.TextField(blank=True, help_text='Optional caption for the video', verbose_name='Legenda')),
            ],
            options={
                'verbose_name': 'Vídeo Curto',
                'verbose_name_plural': 'Vídeos Curtos',
            },
            bases=('events.event',),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='fps',
            field=models.FloatField(blank=True, help_text='Frames per second for video files', null=True, verbose_name='FPS'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='video_bitrate',
            field=models.PositiveIntegerField(blank=True, help_text='Video bitrate in bits per second', null=True, verbose_name='Bitrate do Vídeo'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='video_codec',
            field=models.CharField(blank=True, help_text='Video codec information (e.g., h264, vp9)', max_length=50, null=True, verbose_name='Codec do Vídeo'),
        ),
        migrations.AlterUniqueTogether(
            name='photoseriesfile',
            unique_together={('photo_series', 'media_file'), ('photo_series', 'order')},
        ),
        migrations.AddIndex(
            model_name='photoseriesfile',
            index=models.Index(fields=['photo_series', 'media_file'], name='photoseries_file_media_idx'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='media_file',
            field=models.OneToOneField(help_text='The media file containing the video', on_delete=django.db.models.deletion.CASCADE, to='mediafiles.mediafile', verbose_name='Arquivo de Mídia'),
        ),
    ]
