# Generated by Django 5.2.1 on 2025-06-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediafiles', '0005_videoclip_mediafile_fps_mediafile_video_bitrate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoclip',
            name='media_file',
        ),
        migrations.AddField(
            model_name='videoclip',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração em segundos'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='file_id',
            field=models.CharField(blank=True, help_text='FilePond file identifier', max_length=100, null=True, verbose_name='File ID'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do Arquivo'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Video height in pixels', null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Original'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='video_codec',
            field=models.CharField(blank=True, help_text='Video codec information (e.g., h264, vp9)', max_length=50, null=True, verbose_name='Codec do Vídeo'),
        ),
        migrations.AddField(
            model_name='videoclip',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Video width in pixels', null=True, verbose_name='Largura'),
        ),
    ]
